[app]
name = "boilerplate-golang"
port = 8080
env = "development"

[database]
# Uncomment and configure these settings to enable database connection
# host = "localhost"
# port = 3306
# user = "root"
# password = ""
# name = "boilerplate"
# charset = "utf8mb4"
# parse_time = true
# loc = "Local"
# timeout = "10s"

[redis]
# Uncomment and configure these settings to enable Redis connection
# host = "localhost"
# port = 6379
# password = ""
# db = 0

[jwt]
secret_key = "your-secret-key-here"
access_token_expiry = "15m"
refresh_token_expiry = "24h"